name: weather_animation
description: The package contains beautiful weather animations. Easy setup with the weather configurator!
homepage: https://t.me/+AkGV73kZi_Q1YTMy
repository: https://github.com/PackRuble/weather_animation
issue_tracker: https://github.com/PackRuble/weather_animation/issues

version: 1.2.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  build_runner: ^2.10.5
  lint: ^2.8.0

screenshots:
  - description: 'Weather configurator'
    path: example/weathunits_configurator/assets/weather_configurator_screen.png
  - description: 'Preset weather scenes'
    path: images/all_scenes_scr.png

funding:
  - https://t.me/+AkGV73kZi_Q1YTMy

topics:
  - weather
  - animation
  - ui
  - widgets
  - with-playground