name: weathunits_configurator
description: Handy configurator for creating weather scenes.
publish_to: none

version: 1.1.1+5

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  weather_animation:
    path: ../../../weather_animation # for development
#    git:
#      url: https://github.com/PackRuble/weather_animation

  flutter_riverpod: ^3.2.0
  nanoid: ^1.0.0
  flutter_colorpicker: ^1.1.0
  multi_split_view: ^3.6.1
  flex_color_scheme: ^8.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  lint: ^2.8.0

flutter:
  uses-material-design: true
